"""
PySpark Settings for corona_sentiment_analysis

Generated by 'pysparkcli [command] options' using Python 3.6.

For more information on this file, see
https://code.qburst.com/jinoj/pyspark-cli/1.0.1/topics/settings/
"""
import socket


DEBUG = True
MASTER_URL = 'local[*]'
APP_NAME = 'corona_sentiment_analysis'
DATA_SOURCE = 'localhost'
DATA_SOURCE_PORT = 5555

# Environment Specific Settings
DEVELOPMENT_HOST = ['localhost']
LIVE_HOSTS = []

# Configure environment specific settings
# Create a 'local.py' settings file in your settings and update it with
# your development environment specific values. Add any new environment-specific values that you add to the 'local.py'
# also to 'local_sample.py'
try:
    if socket.gethostname() in DEVELOPMENT_HOST:
        from .local import *
    elif socket.gethostname() in LIVE_HOSTS:
        from .production import *
except Exception as e:
    raise Exception("Cannot determine execution mode for host '%s'.  "
                    "Please check DEVELOPMENT_HOST and LIVE_HOSTS in settings.py." % socket.gethostname())