# Generated by Django 2.2.11 on 2020-04-02 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corona_tweet_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='created_or_modified_by',
            new_name='created_by',
        ),
    ]
