# Generated by Django 2.2.11 on 2020-04-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona_tweet_analysis', '0003_auto_20200402_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
